export const initialVideos = [
  {
    id: "v1",
    source: "youtube",
    source_video_id: "yt-101",
    title: "[대회] 2026 남양주시장기 리그 - 새싹부 vs 마포자이언츠",
    thumbnail_url: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&auto=format&fit=crop&q=60",
    published_at: "2026-06-18T14:30:00Z",
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    team_division: "새싹부",
    tournament: "남양주시장기 리그",
    opponent: "마포자이언츠",
    parsed_status: "success",
    home_team: "구구불독스 새싹부",
    away_team: "마포자이언츠",
    home_score: 8,
    away_score: 5
  },
  {
    id: "v2",
    source: "youtube",
    source_video_id: "yt-102",
    title: "[전국대회] 2026 백호기 전국대회 - 꿈나무부 vs 성동레인보우 8강전",
    thumbnail_url: "https://images.unsplash.com/photo-1605018696950-0972e5631217?w=800&auto=format&fit=crop&q=60",
    published_at: "2026-06-15T11:00:00Z",
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    team_division: "꿈나무부",
    tournament: "백호기 전국대회",
    opponent: "성동레인보우",
    parsed_status: "success",
    home_team: "구구불독스 꿈나무부",
    away_team: "성동레인보우",
    home_score: 10,
    away_score: 3
  },
  {
    id: "v3",
    source: "soop",
    source_video_id: "soop-201",
    title: "구구불독스 유소년부 vs 송파유니콘스 - U13 주말리그 4차전",
    thumbnail_url: "https://images.unsplash.com/photo-1530541930197-ff16ac917b0e?w=800&auto=format&fit=crop&q=60",
    published_at: "2026-06-12T09:15:00Z",
    url: "https://www.sooplive.com",
    team_division: "유소년부",
    tournament: "U13 주말리그",
    opponent: "송파유니콘스",
    parsed_status: "success",
    home_team: "구구불독스 유소년부",
    away_team: "송파유니콘스",
    home_score: 4,
    away_score: 6
  },
  {
    id: "v4",
    source: "youtube",
    source_video_id: "yt-103",
    title: "[친선] 새싹부 vs 광진리틀 야구단 친선 경기",
    thumbnail_url: "https://images.unsplash.com/photo-1471295268307-f13dff427f25?w=800&auto=format&fit=crop&q=60",
    published_at: "2026-06-08T16:00:00Z",
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    team_division: "새싹부",
    tournament: "친선경기",
    opponent: "광진리틀",
    parsed_status: "success",
    home_team: "구구불독스 새싹부",
    away_team: "광진리틀",
    home_score: 12,
    away_score: 2
  },
  {
    id: "v5",
    source: "soop",
    source_video_id: "soop-202",
    title: "[VOD] 꿈나무부 vs 강남블루스 - 꿈나무 리그 예선 2차전",
    thumbnail_url: "https://images.unsplash.com/photo-1516738901171-8eb4fc13bd20?w=800&auto=format&fit=crop&q=60",
    published_at: "2026-06-05T13:45:00Z",
    url: "https://www.sooplive.com",
    team_division: "꿈나무부",
    tournament: "꿈나무 리그",
    opponent: "강남블루스",
    parsed_status: "success",
    home_team: "구구불독스 꿈나무부",
    away_team: "강남블루스",
    home_score: 4,
    away_score: 5
  },
  {
    id: "v6",
    source: "youtube",
    source_video_id: "yt-104",
    title: "유소년부 vs 동작네이비 - U15 전국선수권대회 본선",
    thumbnail_url: "https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=800&auto=format&fit=crop&q=60",
    published_at: "2026-06-02T10:00:00Z",
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    team_division: "유소년부",
    tournament: "U15 전국선수권대회",
    opponent: "동작네이비",
    parsed_status: "success",
    home_team: "구구불독스 유소년부",
    away_team: "동작네이비",
    home_score: 7,
    away_score: 7
  },
  {
    id: "v7",
    source: "youtube",
    source_video_id: "yt-105",
    title: "20260528 구구 vs 용산",
    thumbnail_url: "https://images.unsplash.com/photo-1544045560-72977a472c3f?w=800&auto=format&fit=crop&q=60",
    published_at: "2026-05-28T17:20:00Z",
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    team_division: "미분류",
    tournament: "",
    opponent: "용산",
    parsed_status: "pending",
    home_team: "구구불독스",
    away_team: "용산",
    home_score: null,
    away_score: null
  }
];
